\i init.sql
\i add_role_data.sql
\i add_test_users.sql
\i add_user_roles_view.sql
\i insert_auth_funcs.sql
\i insert_data_funcs.sql
\i add_detection_removals_view.sql
\i add_detections.sql
\i fix_datetime_for_detections.sql
