alter extension pgcrypto drop function armor(bytea);
alter extension pgcrypto drop function armor(bytea, text[], text[]);
alter extension pgcrypto drop function dearmor(text);
alter extension pgcrypto drop function decrypt(bytea, bytea, text);
alter extension pgcrypto drop function decrypt_iv(bytea, bytea, bytea, text);
alter extension pgcrypto drop function digest(bytea, text);
alter extension pgcrypto drop function digest(text, text);
alter extension pgcrypto drop function encrypt(bytea, bytea, text);
alter extension pgcrypto drop function encrypt_iv(bytea, bytea, bytea, text);
alter extension pgcrypto drop function gen_random_bytes(integer);
alter extension pgcrypto drop function hmac(bytea, bytea, text);
alter extension pgcrypto drop function hmac(text, text, text);
alter extension pgcrypto drop function pgp_armor_headers(text, OUT key text, OUT value text);
alter extension pgcrypto drop function pgp_key_id(bytea);
alter extension pgcrypto drop function pgp_pub_decrypt(bytea, bytea);
alter extension pgcrypto drop function pgp_pub_decrypt(bytea, bytea, text);
alter extension pgcrypto drop function pgp_pub_decrypt(bytea, bytea, text, text);
alter extension pgcrypto drop function pgp_pub_decrypt_bytea(bytea, bytea);
alter extension pgcrypto drop function pgp_pub_decrypt_bytea(bytea, bytea, text);
alter extension pgcrypto drop function pgp_pub_decrypt_bytea(bytea, bytea, text, text);
alter extension pgcrypto drop function pgp_pub_encrypt(text, bytea);
alter extension pgcrypto drop function pgp_pub_encrypt(text, bytea, text);
alter extension pgcrypto drop function pgp_pub_encrypt_bytea(bytea, bytea);
alter extension pgcrypto drop function pgp_pub_encrypt_bytea(bytea, bytea, text);
alter extension pgcrypto drop function pgp_sym_decrypt(bytea, text);
alter extension pgcrypto drop function pgp_sym_decrypt(bytea, text, text);
alter extension pgcrypto drop function pgp_sym_decrypt_bytea(bytea, text);
alter extension pgcrypto drop function pgp_sym_decrypt_bytea(bytea, text, text);
alter extension pgcrypto drop function pgp_sym_encrypt(text, text);
alter extension pgcrypto drop function pgp_sym_encrypt(text, text, text);
alter extension pgcrypto drop function pgp_sym_encrypt_bytea(bytea, text);
alter extension pgcrypto drop function pgp_sym_encrypt_bytea(bytea, text, text);

drop function armor(bytea);
drop function armor(bytea, text[], text[]);
drop function dearmor(text);
drop function decrypt(bytea, bytea, text);
drop function decrypt_iv(bytea, bytea, bytea, text);
drop function digest(bytea, text);
drop function digest(text, text);
drop function encrypt(bytea, bytea, text);
drop function encrypt_iv(bytea, bytea, bytea, text);
drop function gen_random_bytes(integer);
drop function hmac(bytea, bytea, text);
drop function hmac(text, text, text);
drop function pgp_armor_headers(text, OUT key text, OUT value text);
drop function pgp_key_id(bytea);
drop function pgp_pub_decrypt(bytea, bytea);
drop function pgp_pub_decrypt(bytea, bytea, text);
drop function pgp_pub_decrypt(bytea, bytea, text, text);
drop function pgp_pub_decrypt_bytea(bytea, bytea);
drop function pgp_pub_decrypt_bytea(bytea, bytea, text);
drop function pgp_pub_decrypt_bytea(bytea, bytea, text, text);
drop function pgp_pub_encrypt(text, bytea);
drop function pgp_pub_encrypt(text, bytea, text);
drop function pgp_pub_encrypt_bytea(bytea, bytea);
drop function pgp_pub_encrypt_bytea(bytea, bytea, text);
drop function pgp_sym_decrypt(bytea, text);
drop function pgp_sym_decrypt(bytea, text, text);
drop function pgp_sym_decrypt_bytea(bytea, text);
drop function pgp_sym_decrypt_bytea(bytea, text, text);
drop function pgp_sym_encrypt(text, text);
drop function pgp_sym_encrypt(text, text, text);
drop function pgp_sym_encrypt_bytea(bytea, text);
drop function pgp_sym_encrypt_bytea(bytea, text, text);
